version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.7-stretch-node
    executor: default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
